name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
       
       ls
       sudo apt install npm
       ls
       sudo apt upgrade
       sudo su
       sudo apt install git
       git clone https://github.com/developerSWe4b/whatsapp-bot.git
       ls
       ls
       cd whatsapp-bot
      
       bash install.sh
       node app.js
